version: "3.4"

services:
  src:
    image: src
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
      - 443
      depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Pandemia2020!"
      ACCEPT_EULA: "Y"
    ports:
      - 1435:1435
